apiVersion: v1
kind: Secret
metadata:
  name: {{ template "abyss.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "abyss.labels" (dict "context" . "component" "server" "name" "secret") | nindent 4 }}
    {{- with .Values.configs.secret.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configs.secret.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
data:
  MYSQL_HOST: {{ include "abyss.mysql.host" . | b64enc | quote }}
  MYSQL_PORT: {{ include "abyss.mysql.port" . | b64enc | quote }}
  MYSQL_USERNAME: {{ default "root" .Values.mysql.auth.username | b64enc | quote }}
  {{- if not .Values.mysql.auth.existingSecret }}
  MYSQL_PASSWORD: {{ default "password" .Values.mysql.auth.password | b64enc | quote }}
  {{- end }}
  MYSQL_DATABASE: {{ default "unlight" .Values.mysql.auth.database | b64enc | quote }}
  DATABASE_URL: {{ include "abyss.mysql.url" . | b64enc | quote }}
  MEMCACHED_HOST: {{ printf "%s:%s" (include "abyss.memcached.host" .) (include "abyss.memcached.port" .) | b64enc | quote }}
