apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: {{ template "shell.server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "shell.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "shell.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shell.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 8 }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.server.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "shell.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 8 }}
    spec:
      {{- with .Values.server.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.server.name }}
          image: {{ default .Values.global.image.repository .Values.server.image.repository }}:{{ default (include "shell.defaultTag" .) .Values.server.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.imagePullPolicy .Values.server.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
