apiVersion: v1
kind: Service
metadata:
  name: {{ template "shell.server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "shell.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
{{- if .Values.server.service.labels }}
{{- toYaml .Values.server.service.labels | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.server.service.httpPort }}
    targetPort: 80
    {{- if eq .Values.server.service.type "NodePort" }}
    nodePort: {{ .Values.server.service.nodePort }}
    {{- end }}
  selector:
    {{- include "shell.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 4 }}
